twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/assets/images': images
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form_theme/fields.html.twig'

when@test:
    twig:
        strict_variables: true
